# Generated by Django 4.2.23 on 2025-06-17 09:42

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_voucher', '0020_alter_historicalworkervoucher_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkervoucher',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkervoucher',
            name='end_time',
            field=core.fields.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkervoucher',
            name='negotiated',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkervoucher',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkervoucher',
            name='start_time',
            field=core.fields.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkervoucher',
            name='work_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workervoucher',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workervoucher',
            name='end_time',
            field=core.fields.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workervoucher',
            name='negotiated',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workervoucher',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workervoucher',
            name='start_time',
            field=core.fields.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workervoucher',
            name='work_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
