# Generated by Django 4.2.23 on 2025-06-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker_voucher", "0021_historicalworkervoucher_activity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalworkervoucher",
            name="negotiated",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalworkervoucher",
            name="paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workervoucher",
            name="negotiated",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workervoucher",
            name="paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
