# Generated by Django 4.2.23 on 2025-08-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker_voucher", "0022_alter_historicalworkervoucher_negotiated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupofworker",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalgroupofworker",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalvoucherformdraft",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalvoucherformdraftdaterangesdetails",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalvoucherformdraftworkersdetails",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalworkergroup",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalworkerupload",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalworkervoucher",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="voucherformdraft",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="voucherformdraftdaterangesdetails",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="voucherformdraftworkersdetails",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="workergroup",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="workerupload",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="workervoucher",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
    ]
