# Generated by Django 4.2.23 on 2025-08-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worker_voucher", "0025_groupofworker_bill_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupofworker",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="historicalgroupofworker",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="historicalvoucherformdraft",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="historicalvoucherformdraftdaterangesdetails",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="historicalvoucherformdraftworkersdetails",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="historicalworkergroup",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="historicalworkerupload",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="historicalworkervoucher",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="voucherformdraft",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="voucherformdraftdaterangesdetails",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="voucherformdraftworkersdetails",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="workergroup",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="workerupload",
            name="bill_code",
        ),
        migrations.RemoveField(
            model_name="workervoucher",
            name="bill_code",
        ),
    ]
