# Generated by Django 4.2.23 on 2025-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker_voucher", "0028_alter_groupofworker_bill_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupofworker",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroupofworker",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalvoucherformdraft",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalvoucherformdraftdaterangesdetails",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalvoucherformdraftworkersdetails",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalworkergroup",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalworkerupload",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalworkervoucher",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="voucherformdraft",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="voucherformdraftdaterangesdetails",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="voucherformdraftworkersdetails",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workergroup",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workerupload",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workervoucher",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
    ]
